@echo off
SETLOCAL

SET "TARGET_PATH=%1"
SET "TARGET_NAME=%~n1"
SET "DEST_DIR=bin\Dll"

IF NOT EXIST "%DEST_DIR%\" MKDIR "%DEST_DIR%"

SET "NEW_TARGET_PATH=%DEST_DIR%\%TARGET_NAME%%~x1"

MOVE "%TARGET_PATH%" "%NEW_TARGET_PATH%"

IF EXIST "%NEW_TARGET_PATH%" (
	ECHO Successfully moved %TARGET_NAME%%~x1 to %DEST_DIR%\
) ELSE (
	ECHO Failed to move %TARGET_NAME%%~x1 to %DEST_DIR%\
	EXIT /B 1
)